[package]
name = "car-rust"
version = "0.1.0"
authors = ["hearsay123 <admin@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
